language: go

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - go get ./...
  - go get golang.org/x/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - make test

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci
